server:
  port: 8082

spring:
  profiles:
    active: test
  application:
    name: jiazm-practice
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    dynamic:
      #主数据源
      primary: master
      strict: false
      datasource:
        #pgsql数据源配置
        master:
          url: jdbc:mysql://60.205.247.48:3306/gpt
          username: jiazm3
          password: jiazm3
          type: com.alibaba.druid.pool.DruidDataSource



logging:
  level:
    root: info
    com.jiazm.practice: debug

