#java包前缀,demo换项目名
bussi_package=com.jiazm
#-------- ----- ----- ----- ----- 数据库 ----- ----- ----- ----- ----- ----- ------
##############################     mysql     ##############################
url: jdbc:mysql://182.92.110.105:3306/jiazm3_test?useUnicode=true&useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
username: jiazm3_test
#password: ENC(s8JmcGF6czKUx00WSxx+cIAPh1jtK4d9)
password: ld612522

#add mima
database_name=jiazm3_test
source_root_package=src.main.java
webroot_package=src.main.webapp